version: '2.4'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ajeet
      POSTGRES_PASSWORD: ajeet
      POSTGRES_DB: cdrdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ajeet -d cdrdb" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
      - init-data:/docker-entrypoint-initdb.d
    networks:
      - backend
  ms:
    image: phone_record_ms:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cdrdb
      SPRING_DATASOURCE_USERNAME: ajeet
      SPRING_DATASOURCE_PASSWORD: ajeet
      POSTGRES_DB: cdrdb
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
networks:
  backend:

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/data/store
  init-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/data/init
